# Regular Expressions and Python Libraries

### Regular Expressions (Regex)

In [ ]:
import re

# Basic pattern matching
text = "The quick brown fox jumps over the lazy dog"
pattern = r"fox"

# Search for pattern
match = re.search(pattern, text)
if match:
    print(f"Found '{pattern}' at position {match.start()}-{match.end()}")

# Find all occurrences
text2 = "The cat and the bat sat on the mat"
pattern2 = r"\b\w*at\b"  # Words ending with 'at'
matches = re.findall(pattern2, text2)
print(f"Words ending with 'at': {matches}")

In [ ]:
# Common regex patterns
test_strings = [
    "john@example.com",
    "invalid-email",
    "123-456-7890",
    "(555) 123-4567",
    "not-a-phone",
    "2024-01-15",
    "15/01/2024"
]

# Email pattern
email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# Phone pattern
phone_pattern = r'^(\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4})$'

# Date pattern (YYYY-MM-DD)
date_pattern = r'^\d{4}-\d{2}-\d{2}$'

for string in test_strings:
    print(f"Testing: '{string}'")
    print(f"  Email: {bool(re.match(email_pattern, string))}")
    print(f"  Phone: {bool(re.match(phone_pattern, string))}")
    print(f"  Date: {bool(re.match(date_pattern, string))}")
    print()

In [ ]:
# Text substitution with regex
text = "Visit our website at http://example.com or https://secure.example.com"

# Replace URLs with placeholder
url_pattern = r'https?://[\w.-]+'
cleaned_text = re.sub(url_pattern, '[URL]', text)
print(f"Original: {text}")
print(f"Cleaned: {cleaned_text}")

# Extract and format phone numbers
phone_text = "Call me at 123-456-7890 or (555) 123-4567"
phone_pattern = r'(\(?\d{3}\)?)[-.\s]?(\d{3})[-.\s]?(\d{4})'
formatted_phones = re.sub(phone_pattern, r'(\1) \2-\3', phone_text)
print(f"\nOriginal phones: {phone_text}")
print(f"Formatted phones: {formatted_phones}")

### NumPy - Numerical Computing

abcodshfdorfniu

abcodshfdorfniu.add()

import abcodshfdorfniu as abc

abc.add()


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  #[1, 2, 3, 4, 5] type list 

In [3]:
type(arr1)

numpy.ndarray

In [28]:
arr1 ## Type 
"""
1 = True
2 = False
"""
arr2 = np.array([[0, 0, 0], [1, 0, 0]])
arr2

array([[0, 0, 0],
       [1, 0, 0]])

In [ ]:
arr2.all()

In [17]:
arr2.any()

np.False_

In [20]:
arr2.argmax()

np.int64(3)

In [22]:
arr2.argmin()

np.int64(0)

In [26]:
arr2.argpartition(2)

array([[0, 1, 2],
       [1, 2, 0]])

In [38]:
arr1 = np.array([2,1,3,5,4]) # -> 1,2,3,4,5

"""
2 - > 0 -> 1
1 -> 1 -> 0
3 -> 2 -> 2
5 -> 3 -> 4
4 -> 4 -> 3

1,2,3,4,5

"""

'\n2 - > 0 -> 1\n1 -> 1 -> 0\n3 -> 2 -> 2\n5 -> 3 -> 4\n4 -> 4 -> 3\n\n1,2,3,4,5\n\n'

In [33]:
arr1.sort()

In [39]:
arr1.argsort()

array([1, 0, 2, 4, 3])

In [54]:
arr1.astype(np.float16).dtype

dtype('float16')

In [71]:
arr1 = np.array([1, 2, 3, 4, 5,555])

In [72]:
#np.choose(a,choice)

In [73]:
arr1.clip(2,10)

array([ 2,  2,  3,  4,  5, 10])

In [77]:
arr1.compress(arr1>2)

array([  3,   4,   5, 555])

In [86]:
arr2.conj()

array([[0, 0, 0],
       [1, 0, 0]])

In [88]:
import copy

original_list = [[1, 2], [3, 4]]
shallow_copied_list = copy.copy(original_list)

shallow_copied_list[0].append(5) # Modifies the nested list

print(original_list)       # Output: [[1, 2, 5], [3, 4]]
print(shallow_copied_list) # Output: [[1, 2, 5], [3, 4]]

[[1, 2, 5], [3, 4]]
[[1, 2, 5], [3, 4]]


In [90]:
arr3 = arr2.copy()

In [96]:
arr3[0][0] = 1

In [97]:
arr3

array([[1, 0, 0],
       [1, 0, 0]])

In [101]:
arr1

array([  1,   2,   3,   4,   5, 555])

In [104]:
arr1.cumsum()

array([  1,   3,   6,  10,  15, 570])

In [105]:
arr2.diagonal()

array([0, 0])

In [117]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
arr3 = np.array([[3,2,1], [4, 5, 6], [7,7,9]])

In [111]:
arr2.diagonal()

array([1, 5, 9])

In [128]:
np.zeros((4,16))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [131]:
arr2[(arr2>2) & (arr2%3 == 0)]

array([3, 6, 9])

In [80]:
arr1[arr1>2]

array([  3,   4,   5, 555])

In [ ]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print(f"1D array: {arr1}")
print(f"2D array:\n{arr2}")
print(f"Zeros:\n{zeros}")
print(f"Range array: {range_arr}")
print(f"Linspace array: {linspace_arr}")

In [ ]:
# Array operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")
print(f"Square: {a ** 2}")
print(f"Sum: {np.sum(a)}")
print(f"Mean: {np.mean(a)}")
print(f"Standard deviation: {np.std(a)}")

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(f"\nMatrix multiplication:\n{np.dot(matrix1, matrix2)}")

### Pandas - Data Analysis

In [132]:
import pandas as pd

# Creating DataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Salary': [50000, 60000, 70000, 55000]
}


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dhanu\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\dhanu\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\dhanu\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import

In [ ]:
import pandas as pd

# Creating DataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Salary': [50000, 60000, 70000, 55000]
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print(f"\nDataFrame info:")
print(df.info())
print(f"\nBasic statistics:")
print(df.describe())

In [ ]:
# Data manipulation
print("Selecting columns:")
print(df['Name'])
print("\nFiltering data (Age > 28):")
print(df[df['Age'] > 28])

# Adding new column
df['Bonus'] = df['Salary'] * 0.1
print("\nWith bonus column:")
print(df)

# Grouping and aggregation
city_stats = df.groupby('City').agg({
    'Age': 'mean',
    'Salary': ['mean', 'sum']
})
print("\nGrouped by city:")
print(city_stats)

### Matplotlib - Data Visualization

In [ ]:
import matplotlib.pyplot as plt

# Simple line plot
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y, label='sin(x)')
plt.plot(x, np.cos(x), label='cos(x)')
plt.xlabel('X values')
plt.ylabel('Y values')
plt.title('Sine and Cosine Functions')
plt.legend()
plt.grid(True)
plt.show()

# Bar chart
categories = ['A', 'B', 'C', 'D']
values = [23, 45, 56, 78]

plt.figure(figsize=(8, 6))
plt.bar(categories, values, color=['red', 'green', 'blue', 'orange'])
plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Sample Bar Chart')
plt.show()

In [ ]:
# Scatter plot and histogram
np.random.seed(42)
x_scatter = np.random.randn(100)
y_scatter = np.random.randn(100)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Scatter plot
ax1.scatter(x_scatter, y_scatter, alpha=0.6)
ax1.set_xlabel('X values')
ax1.set_ylabel('Y values')
ax1.set_title('Scatter Plot')

# Histogram
ax2.hist(x_scatter, bins=20, alpha=0.7, color='skyblue')
ax2.set_xlabel('Values')
ax2.set_ylabel('Frequency')
ax2.set_title('Histogram')

plt.tight_layout()
plt.show()